pipeline:
  name: pd-one-pipleine
  identifier: pdonepipleine
  projectIdentifier: SFTY_Training
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: build
        identifier: build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec:
              size: flex
              imageSpec:
                imageName: ubuntu-24
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: pddockerhub
                    repo: pavandath510/harness-py-app
                    tags:
                      - v3
  properties:
    ci:
      codebase:
        connectorRef: pdonegiit
        repoName: python-app
        build: <+input>
        sparseCheckout: []
