pipeline:
  name: pd-cicd-pipeliine
  identifier: pdcicdpipeliine
  projectIdentifier: SFTY_Training
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: pavandathgithub
        repoName: python-app
        build: <+input>
  stages:
    - stage:
        name: Build Python App
        identifier: Build_Python_App
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec:
              size: flex
              imageSpec:
                imageName: ubuntu-24
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: pddockerhub
                    repo: pavandath510/harness-py-app
                    tags:
                      - latest
    - stage:
        name: deploy-in-k8s
        identifier: deployink8s
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: webapplication
          environment:
            environmentRef: pdtestenv
            deployToAll: false
            infrastructureDefinitions:
              - identifier: pdinfra
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
              - step:
                  type: HarnessApproval
                  name: pod-deletion
                  identifier: poddeletion
                  spec:
                    approvalMessage: Should I delete the pods?
                    includePipelineExecutionHistory: true
                    isAutoRejectEnabled: false
                    approvers:
                      userGroups:
                        - account._account_all_users
                      minimumCount: 1
                      disallowPipelineExecutor: false
                    approverInputs:
                      - name: action
                        defaultValue: ""
                        description: Please select an option
                        required: true
                        selectOneFrom: delete,keep
                  timeout: 1d
              - parallel:
                  - step:
                      type: ShellScript
                      name: keep-pods
                      identifier: keeppods
                      spec:
                        shell: Bash
                        executionTarget: {}
                        source:
                          type: Inline
                          spec:
                            script: |
                              #!/bin/bash
                              echo "Approver chose KEEP — no pods were deleted."
                        environmentVariables: []
                        outputVariables: []
                      timeout: 10m
                      when:
                        stageStatus: Success
                        condition: |
                          <+steps.poddeletion.output.approverInputs.action> == "keep"
                  - step:
                      type: K8sDelete
                      name: K8sDelete_1
                      identifier: K8sDelete_1
                      spec:
                        deleteResources:
                          type: ResourceName
                          spec:
                            resourceNames:
                              - deployment/python-app
                              - service/python-app-svc
                      timeout: 10m
                      when:
                        stageStatus: Success
                        condition: |
                          <+steps.poddeletion.output.approverInputs.action> == "delete"
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
