pipeline:
  name: pd-ai-rollback
  identifier: pdairollback
  projectIdentifier: SFTY_Training
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Deploy Python App
        identifier: Deploy_Python_App
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: webapplication
          environment:
            environmentRef: pdtestenv
            deployToAll: false
            infrastructureDefinitions:
              - identifier: pdinfra
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
