pipeline:
  name: pd-e2e
  identifier: pde2e
  projectIdentifier: SFTY_Training
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: SonarQube
        identifier: SonarQube
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec:
              size: flex
              imageSpec:
                imageName: ubuntu-24
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |-
                      mvn clean verify sonar:sonar \
                        -Dsonar.projectKey=harness \
                        -Dsonar.host.url=http://34.121.101.248:9000 \
                        -Dsonar.login=sqp_67f87e20480e5d4037760181566f5e8553373fe3
  properties:
    ci:
      codebase:
        connectorRef: pavandathgithub
        repoName: spring-petclinic
        build: <+input>
