pipeline:
  name: pd-e2e
  identifier: pde2e
  projectIdentifier: SFTY_Training
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: SonarQube
        identifier: SonarQube
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec:
              size: flex
              imageSpec:
                imageName: ubuntu-24
          execution:
            steps:
              - step:
                  type: Sonarqube
                  name: Sonarqube_1
                  identifier: Sonarqube_1
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: repository
                      detection: manual
                      name: sonar
                      variant: main
                    advanced:
                      log:
                        level: info
                    auth:
                      access_token: sqp_9bf48e11fb4f6a25ae41576016eb47d915150906
                      domain: http://34.121.101.248:9000/
                      ssl: false
  properties:
    ci:
      codebase:
        connectorRef: pavandathgithub
        repoName: spring-petclinic
        build: <+input>
