pipeline:
  name: pd-GCP-MIG-UC
  identifier: pdGCPMIGUC
  projectIdentifier: SFTY_Training
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: mig
        identifier: mig
        description: ""
        type: IACM
        spec:
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          workspace: pdmiggcp
          execution:
            steps:
              - step:
                  type: IACMTerraformPlugin
                  name: init
                  identifier: init
                  timeout: 10m
                  spec:
                    command: init
              - step:
                  type: IACMTerraformPlugin
                  name: plan
                  identifier: plan
                  timeout: 10m
                  spec:
                    command: plan
              - step:
                  type: IACMTerraformPlugin
                  name: IACMTerraformPlugin_4
                  identifier: IACMTerraformPlugin_4
                  spec:
                    command: destroy
                  timeout: 1h
        tags: {}
