pipeline:
  name: pd-test-pipe
  identifier: pdtestpipe
  projectIdentifier: SFTY_Training
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: pavandathgithub
        repoName: python-app
        build: <+input>
        sparseCheckout: []
  stages:
    - stage:
        name: Ci
        identifier: Ci
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec:
              size: flex
              imageSpec:
                imageName: ubuntu-24
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: pddockerhub
                    repo: pavandath510/harness-py-app
                    tags:
                      - v2
